In [1]:
# First things first, we should import that we'll use library.
import tensorflow as tf

In [2]:
# Let's check version of TensorFlow Library.
tf.__version__

'2.17.0'

In [3]:
# Let's create a new 0-D (zero dimension) Tensor.
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
# Let's create a new 1-D (one dimension) Tensor and then we analyze parameters of "tf.constant()" method.
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
# As u see, If only one element in the tensor is of type float, the type of the Tensor will be float.
tensor_one_d_float = tf.constant([2,0,-3.])
print(tensor_one_d_float)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [6]:
# Now we will create a 2-D (two dimension) Tensor and then we shall analyze the output.
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [7]:
# Create a 3-D (three dimesion) Tensor.
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [8]:
# The ndim attribute in Python is used to determine the number of dimensions of an array or similar data structure.
print(tensor_three_d.ndim, tensor_two_d.ndim, tensor_one_d.ndim)

3 2 1


In [9]:
# We look at the "tf.cast()" method together for casting operations (It uses to convert type of Tensors)
tensor_one_d_ = tf.constant([2,0.,-3,8.,90], dtype = tf.float32)
casted_tensor_ = tf.cast(tensor_one_d_, dtype = tf.int16)

print(tensor_one_d_)
print(casted_tensor_)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [10]:
# Create our own boolean tensor
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [11]:
# Create our own string tensor
tensor_string = tf.constant(["hello world", "hi, how are you?"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi, how are you?'], shape=(2,), dtype=string)


In [12]:
import numpy as np

In [13]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [14]:
# Convert the above NumPy array to a TensorFlow Tensor using "tf.convert_to_tensor"
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


**What is the identity matrix ?**

* An identity matrix is a matrix where the diagonal elements are 1 and all other elements are 0. This matrix is particularly useful in linear algebra,especially in multiplication operations.

In [15]:
# Let's create a identity matrix using "tf.eye()"
eye_tensor = tf.eye(num_rows = 3, dtype = tf.float32) # Parameters : tf.eye(num_rows, num_columns, batch_shape, dtype, name) ; only the num_rows parameter must be filled
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
# Let's we learn what is "tf.fill() method" doing example
fill_tensor = tf.fill([3,4], 5) # Parameters : tf.fill(dimensions, value, name = None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [17]:
# Ok, now we will create Tensors using "tf.ones()" and "tf.zeros" functions
ones_tensor = tf.ones([3,4]) # Parameters : tf.ones(shape, dtype = tf.float32, name = None)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [18]:
zeros_tensor = tf.zeros([3,4]) # Parameters : tf.zeros(shape, dtype = float32, name = None)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [19]:
# so, what is "tf.ones_like()" function ?
ones_like_tensor = tf.ones_like(fill_tensor) # Parameters : tf.ones_like(input, dtype = None, name = None)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [20]:
fill_tensor.shape # As you can see, tf.ones_like() created a tensor filled with 1 and shape of this tensor same with fill_tensor.

TensorShape([3, 4])

In [21]:
# Let's we look at "tf.rank()" function
rank_tensor = tf.rank([[11,23,42,17],
                       [32,45,53,12]])
print(rank_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [22]:
rank_tensor_2 = tf.rank(tensor_three_d) # Parameters : tf.rank(input, name = None)
print(rank_tensor_2)

tf.Tensor(3, shape=(), dtype=int32)


In [23]:
# Let's analyze "tf_random_normal()" function.
random_normal_tensor = tf.random.normal(shape = [3,4], mean = 0, stddev = 1) # Parameters : tf.random_normal(shape, mean, stddev, dtype, seed = None, name = None)
print(random_normal_tensor)

tf.Tensor(
[[-2.2102795  -1.4945798  -0.57717717  1.0838962 ]
 [-1.030831    0.37473977  0.86853564 -0.5715423 ]
 [ 0.90669626  1.3768299   0.57659394 -0.9901503 ]], shape=(3, 4), dtype=float32)


In [24]:
# Let's create one more instance
random_normal_tensor_2 = tf.random.normal(shape = [2,5], mean = 10, stddev = 3, dtype = tf.float32)
print(random_normal_tensor_2)

tf.Tensor(
[[ 7.9928703  6.136935   8.449509   7.2694173  7.8304567]
 [ 7.3341126  8.120552   6.9636974  6.041788  10.738607 ]], shape=(2, 5), dtype=float32)


In [25]:
# It's going really well so far, now let's learn "tf.random.uniform()" function doing example
random_uniform_tensor =tf.random.uniform(shape = [3,5], minval = 3, maxval = 5)
print(random_uniform_tensor)

tf.Tensor(
[[3.9093804 3.0016284 4.334711  3.0943427 3.571076 ]
 [3.4043658 3.5807695 4.7093096 4.8017163 4.284114 ]
 [4.480288  3.9964674 4.7459774 4.192663  3.5079935]], shape=(3, 5), dtype=float32)


In [26]:
integer_random_uniform_tensor = tf.random.uniform(random_uniform_tensor.shape, minval = 12, maxval = 30, dtype = tf.int32)
print(integer_random_uniform_tensor)

tf.Tensor(
[[14 26 20 15 13]
 [23 16 12 22 26]
 [28 27 29 18 20]], shape=(3, 5), dtype=int32)


In [27]:
# let's we look at indexing operations on Tensors
tensor_indexed = tf.constant([2,4,9,0,4,5,6,7])
print(tensor_indexed[3])

tf.Tensor(0, shape=(), dtype=int32)


In [28]:
print(tensor_indexed[7])

tf.Tensor(7, shape=(), dtype=int32)


In [29]:
print(tensor_indexed[-1])

tf.Tensor(7, shape=(), dtype=int32)


In [30]:
tensor_indexed[7] == tensor_indexed[-1]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [31]:
# You can do slicing operations on Tensor, I will give a few example :
print(tensor_indexed[1:4]) # It will take the value at the index of the first parameter but will not take the value at the index of the second parameter.

tf.Tensor([4 9 0], shape=(3,), dtype=int32)


In [32]:
tensor_indexed[2:]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([9, 0, 4, 5, 6, 7], dtype=int32)>

In [33]:
tensor_indexed[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 4, 9, 0, 4], dtype=int32)>

In [34]:
print(tensor_indexed[0:7]) # tensor_indexed[start:end]
print(tensor_indexed[0:7:2]) # tensor_indexed[start:end:step]

tf.Tensor([2 4 9 0 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([2 9 4 6], shape=(4,), dtype=int32)


In [35]:
# At now, lets learn what does argmax() and argmin() functions with examples.
a = tf.constant([2,7,8,3,1,9,0,5]) # argmax() ; It is a function in the TensorFlow library used to find the index of the element with the highest value in the given tensor.
print(tf.argmax(a))

tf.Tensor(5, shape=(), dtype=int64)


In [36]:
b = tf.constant([2,5,6,3,0,4,1,9]) # argmin() ; It is a function in the TensorFlow library used to find the index of the element with the lowest value in the given tensor.
print(tf.argmin(b))

tf.Tensor(4, shape=(), dtype=int64)


In [37]:
# Ok, let's look at the argmax() and argmin() functions on 2-D Tensor
t_argmax = tf.constant([
    [1,2,7,4],
    [2,3,6,3],
    [0,4,3,8]
])
print(tf.argmax(t_argmax))

tf.Tensor([1 2 0 2], shape=(4,), dtype=int64)


In [38]:
t_argmin = tf.constant([
    [11,88,79,92],
    [32,50,97,10],
    [74,62,54,86]
])
print(tf.argmin(t_argmin))

tf.Tensor([0 1 2 1], shape=(4,), dtype=int64)


In [39]:
# If you do 1 value of axis parameter it only looks on rows or do axis 0 value of axis parameter it only looks columns. Let's we check out. (likewise for argmin and argmax)
tensor_argmax = tf.constant([
    [1,2,4,5],
    [23,4,42,11],
    [17,87,54,34],
    [2,0,95,65]
])
print(tf.argmax(tensor_argmax, axis = 0), tf.argmax(tensor_argmax, axis = 1))

tf.Tensor([1 2 3 3], shape=(4,), dtype=int64) tf.Tensor([3 2 1 2], shape=(4,), dtype=int64)


In [40]:
# Let's we check out sigmoid function
sigmoid_tensor = tf.constant([0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0])
print(tf.math.sigmoid(sigmoid_tensor))

tf.Tensor(
[0.5        0.62245935 0.7310586  0.8175745  0.8807971  0.9241418
 0.95257413], shape=(7,), dtype=float32)


In [41]:
matrix_1 = tf.constant([
    [1,2,4],
    [8,9,0],
    [3,4,7]
])

matrix_2 = tf.constant([
    [2,3,4],
    [1,3,0],
    [3,5,2]
])

In [42]:
# Let's look at the "tf.linalg.matmul()" function
print(tf.linalg.matmul(matrix_1, matrix_2)) # matmul() is a function in TensorFlow that helps us multiply two "matrices".

tf.Tensor(
[[16 29 12]
 [25 51 32]
 [31 56 26]], shape=(3, 3), dtype=int32)


# **NOTE**

 If you want to multiply two matrices. You shouldn't forget this :

---

* Column number of first matrix must be equals to row number of second matrix.Otherwise you will get an error and your program will not work properly.

In [43]:
matrix_1@matrix_2 # This gives you same output too

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 29, 12],
       [25, 51, 32],
       [31, 56, 26]], dtype=int32)>

In [44]:
# Well, Do you know how do we inverse of any matrix ? Let's we learn that.
inverse_matrix = tf.constant([
    [2,3,7],
    [4,5,1],
    [9,0,6]
], dtype = tf.float32)
print(tf.linalg.inv(inverse_matrix))

tf.Tensor(
[[-0.1         0.06        0.10666666]
 [ 0.05000001  0.17       -0.08666667]
 [ 0.15       -0.09        0.00666667]], shape=(3, 3), dtype=float32)


In [45]:
# Let's check out einsum function
einsum_tensor_1 = tf.constant([
    [2,5,8],
    [1,3,7]
])

einsum_tensor_2 = tf.constant([
    [6,9],
    [4,2],
    [5,0]
])

print(tf.linalg.einsum("ij,jk->ik", einsum_tensor_1, einsum_tensor_2)) # "ij,jk->ik" statement uses to multiply two matrix
# ij : row and column numbers of first matrix, jk : row and column numbers of second matrix and ik : row and column numbers of new matrix (end of multiply operation).

tf.Tensor(
[[72 28]
 [53 15]], shape=(2, 2), dtype=int32)


In [46]:
# Let's look at the reshape() function
y = tf.constant([2,4,5,6,7,0,9,1])
print(tf.reshape(y, shape = (2,4)))

tf.Tensor(
[[2 4 5 6]
 [7 0 9 1]], shape=(2, 4), dtype=int32)


In [47]:
# Let's we do example using concat() function with axis = 0
x = tf.constant([3,5,7,8,9])
z = tf.constant([1,2,6,4,0])
print(tf.concat([x,z], axis = 0))

tf.Tensor([3 5 7 8 9 1 2 6 4 0], shape=(10,), dtype=int32)


In [48]:
# Let's we create a new instance with axis = 1
e = tf.constant([
    [1,3,12],
    [24,43,71],
    [0,4,9]
])

f = tf.constant([
    [3,6,5],
    [9,8,1],
    [32,65,89]
])

print(tf.concat([e,f], axis = 1))

tf.Tensor(
[[ 1  3 12  3  6  5]
 [24 43 71  9  8  1]
 [ 0  4  9 32 65 89]], shape=(3, 6), dtype=int32)


# **Let's we examine ragged tensors**

In [49]:
# If we would try this on a normal tensor. We would get an error (Error Message : Can't convert non-rectangular Python sequence to Tensor)
ragged_tensor = tf.ragged.constant([
    [1,3],
    [4,5,6],
    [7]
])

In [50]:
# Let's look at some functions of ragged tensor
## boolean_mask() function
tf.ragged.boolean_mask(
  tf.ragged.constant([[1,2,3], [5], [4,8,9]]),
  tf.ragged.constant([[True, True, False], [False], [False, False, True]])).to_list()

[[1, 2], [], [9]]

# **What is the Sparse Tensor ?**

The word sparse means "having very few items, spread out." A Sparse Tensor is a special kind of tensor that contains a lot of zeros. This means that there are very few meaningful values, and the rest are just zeros.


# **Why Do We Use Sparse Tensors?**

Sparse tensors are used to store data more efficiently and perform operations faster because:

* If we have a tensor with a lot of zeros, storing it in the usual way takes up unnecessary space. Instead of storing the zeros, we can store only the non-zero values, which saves memory.

* This way, we can save memory and process data faster.


In [53]:
sparse_tensor = tf.sparse.SparseTensor(
    indices = [[0,0], [2,5]],
    values = [1,9],
    dense_shape = [5,6]
)
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [54]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

# **What is a String Tensor?**

String Tensor is a type of tensor in TensorFlow that contains textual data, or string values. Typically, tensors hold numbers (such as integers or floating-point numbers), but string tensors allow us to work with text data.


# **When Are String Tensors Used?**

-> String tensors are very useful when dealing with text-based data. For example:

* Natural Language Processing (NLP): When we need to process sentences or words in a model, string tensors are used.

* Label Storage: In machine learning models, class labels (like "Cat", "Dog") are often stored as strings using string tensors.

**NOTE :** String tensors, like other tensors, can be one-dimensional (a list) or multi-dimensional (like a table).

In [55]:
string_tensor = tf.constant(["Hello world", "Deep Learning", "Tensorflow"])
string_tensor

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Hello world', b'Deep Learning', b'Tensorflow'], dtype=object)>

In [59]:
tf.strings.join(string_tensor, separator = " - ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world - Deep Learning - Tensorflow'>